@apiUrl = http://localhost:3030/users
#@apiUrl = https://notes-fredde-23.azurewebsites.net/users
@token = {{$dotenv DATABASE_URL}}
@jwt = {{$dotenv JWT}}

###
GET {{apiUrl}}
Authorization: Bearer {{token}}

###
GET {{apiUrl}}/650044d3114495b6a2481466
Authorization: Bearer {{token}}

### Logga in på /users/login
POST {{apiUrl}}/login
Content-Type: application/json

{
    "email": "isak@foo.baz",
    "password": "Password123"
}

### skapa ny användare
POST {{apiUrl}}
Content-Type: application/json

{
    "email": "isak@foo.baz",
    "password": "Password123"
}

### 
PATCH {{apiUrl}}/15
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "changed@gmail.com"
}

###
DELETE {{apiUrl}}/2
Authorization: Bearer {{token}}

###